title: Barashada HTML and CSS oo Afsoomaali ah
description: >-
  Walaaliyaal haddaan nahay soomaali waxa la nooga baahan yahay in aan qeyb weyn
  ka qaadano News ka Technology da Fadlan ku web design and development
  Applications ism.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
